Feature/swaap v1
paraswap/paraswap-dex-lib pull request #225
Opened 2022-11-07 11:22 UTC by Louis-Amas

2022-11-07 14:12 UTC, ColonelJ requested changes

2022-11-07 14:12 UTC, ColonelJ commented on src/dex/swaap-v1/swaap-v1.ts
> +          state = await this.eventPools[poolAddress].generateState(blockNumber);
Should call `setState` with the generated state so that it can possibly be used again.

2022-11-07 14:12 UTC, ColonelJ commented on src/dex/swaap-v1/swaap-v1.ts
> +    );
Can migrate generate/set state and subscribe to logs to using new `initialize` function instead.  It looks like `addressSubscribers` needs renamed everywhere for that to work.

2022-11-09 13:50 UTC, ColonelJ approved these changes

2022-11-09 14:10 UTC, Verisana approved these changes

2022-11-09 14:24 UTC, merged