RadioShack
paraswap/paraswap-dex-lib pull request #71
Opened 2022-03-31 16:08 UTC by radioshackcreator

Adding RadioShack, a Uniswap v2 fork, with a 'starfish' swap pair topology. Learn more here:
https://docs.radioshack.org

App is live here on Polygon and BSC (Avalanche and Ethereum coming soon):
https://app.radioshack.org/swap

2022-03-31 18:04 UTC, ColonelJ requested changes
Hi, if your DEX doesn't need any special logic to deal with dynamic fees or something else, then you don't need to add any `radioshack.ts` you can simply add your forks to the `config.ts`.  You are using a `'swapFee'` function in `radioshack.ts` which doesn't seem to exist in your ABI, so I don't think you have dynamic fees.  So I think nearly all your changes are not needed (don't need your ABI, dedicated config etc.).  Just add to the main `config.ts` your forks and keep the tests you've already done.

2022-04-01 16:14 UTC, shresthagrawal commented on src/dex/uniswap-v2/uniswap-v2-e2e-bsc.test.ts
> +          tokens.WBNB,
```suggestion
          tokens.BNB,
```

2022-04-01 16:14 UTC, shresthagrawal commented on src/dex/uniswap-v2/uniswap-v2-e2e-bsc.test.ts
> +          holders.WBNB,
```suggestion
          holders.BNB,
```

2022-04-01 16:41 UTC, shresthagrawal commented
The e2e tests are failing because the pools doesn't seem to exist for the pairs! Would be good if you can fix the tests and check that it works. You can do that by having the appropriate env variables and running `npx jest -t 'radioshack' src/dex/uniswap-v2/uniswap-v2-e2e-bsc.test.ts` for bsc and `npx jest -t 'radioshack' src/dex/uniswap-v2/uniswap-v2-e2e-polygon.test.ts`for mainnet

2022-04-01 19:13 UTC, shresthagrawal approved these changes
LGTM

2022-04-04 14:57 UTC, ColonelJ approved these changes

2022-04-04 14:58 UTC, merged